<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_596lMPtaEe2jXvmcOqjeoQ" name="Presentación" author="Allen" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_596lMftaEe2jXvmcOqjeoQ" name="Presentación">
      <elements xmi:type="process:Lane" xmi:id="_596lMvtaEe2jXvmcOqjeoQ" name="Empleado (lane) " actor="_596lS_taEe2jXvmcOqjeoQ">
        <elements xmi:type="process:StartEvent" xmi:id="_596lM_taEe2jXvmcOqjeoQ" name="Inicio1" outgoing="_596lSPtaEe2jXvmcOqjeoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_596lNPtaEe2jXvmcOqjeoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_596lNftaEe2jXvmcOqjeoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_596lNvtaEe2jXvmcOqjeoQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_596lN_taEe2jXvmcOqjeoQ" name="Tarea1" incoming="_596lSPtaEe2jXvmcOqjeoQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_596lOPtaEe2jXvmcOqjeoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_596lOftaEe2jXvmcOqjeoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_596lOvtaEe2jXvmcOqjeoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_596lO_taEe2jXvmcOqjeoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_596lPPtaEe2jXvmcOqjeoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_596lPftaEe2jXvmcOqjeoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_596lPvtaEe2jXvmcOqjeoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_596lP_taEe2jXvmcOqjeoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_596lQPtaEe2jXvmcOqjeoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_596lQftaEe2jXvmcOqjeoQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_596lQvtaEe2jXvmcOqjeoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_596lQ_taEe2jXvmcOqjeoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_596lRPtaEe2jXvmcOqjeoQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_596lRftaEe2jXvmcOqjeoQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_596lRvtaEe2jXvmcOqjeoQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_596lR_taEe2jXvmcOqjeoQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_596lSPtaEe2jXvmcOqjeoQ" target="_596lN_taEe2jXvmcOqjeoQ" source="_596lM_taEe2jXvmcOqjeoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_596lSftaEe2jXvmcOqjeoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_596lSvtaEe2jXvmcOqjeoQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_596lS_taEe2jXvmcOqjeoQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_596lTPtaEe2jXvmcOqjeoQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_596lTftaEe2jXvmcOqjeoQ">
        <name xmi:type="expression:Expression" xmi:id="_596lTvtaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_596lT_taEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_596lUPtaEe2jXvmcOqjeoQ">
        <name xmi:type="expression:Expression" xmi:id="_596lUftaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_596lUvtaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_596lU_taEe2jXvmcOqjeoQ">
        <name xmi:type="expression:Expression" xmi:id="_596lVPtaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_596lVftaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_596lVvtaEe2jXvmcOqjeoQ">
        <name xmi:type="expression:Expression" xmi:id="_596lV_taEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_596lWPtaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_596lWftaEe2jXvmcOqjeoQ">
        <name xmi:type="expression:Expression" xmi:id="_596lWvtaEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_596lW_taEe2jXvmcOqjeoQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_596lXPtaEe2jXvmcOqjeoQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_596lXftaEe2jXvmcOqjeoQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_596lXvtaEe2jXvmcOqjeoQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_596lX_taEe2jXvmcOqjeoQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_596lYPtaEe2jXvmcOqjeoQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_596lYftaEe2jXvmcOqjeoQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_596lYvtaEe2jXvmcOqjeoQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_596lY_taEe2jXvmcOqjeoQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_596lZPtaEe2jXvmcOqjeoQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_596lZftaEe2jXvmcOqjeoQ" type="Process" element="_596lMPtaEe2jXvmcOqjeoQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_596lZvtaEe2jXvmcOqjeoQ" type="2007" element="_596lMftaEe2jXvmcOqjeoQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_596lZ_taEe2jXvmcOqjeoQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_596laPtaEe2jXvmcOqjeoQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_596laftaEe2jXvmcOqjeoQ" type="3007" element="_596lMvtaEe2jXvmcOqjeoQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_596lavtaEe2jXvmcOqjeoQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_596la_taEe2jXvmcOqjeoQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_596lbPtaEe2jXvmcOqjeoQ" type="3005" element="_596lN_taEe2jXvmcOqjeoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_596lbftaEe2jXvmcOqjeoQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_596lbvtaEe2jXvmcOqjeoQ" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_596lb_taEe2jXvmcOqjeoQ" type="3002" element="_596lM_taEe2jXvmcOqjeoQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_596lcPtaEe2jXvmcOqjeoQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_596lcftaEe2jXvmcOqjeoQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_596lcvtaEe2jXvmcOqjeoQ" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_596lc_taEe2jXvmcOqjeoQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_596ldPtaEe2jXvmcOqjeoQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_596ldftaEe2jXvmcOqjeoQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_596ldvtaEe2jXvmcOqjeoQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_596ld_taEe2jXvmcOqjeoQ"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_596lePtaEe2jXvmcOqjeoQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_596leftaEe2jXvmcOqjeoQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_596levtaEe2jXvmcOqjeoQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_596le_taEe2jXvmcOqjeoQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_596lfPtaEe2jXvmcOqjeoQ" width="1000" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_596lfftaEe2jXvmcOqjeoQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_596lfvtaEe2jXvmcOqjeoQ" type="4001" element="_596lSPtaEe2jXvmcOqjeoQ" source="_596lb_taEe2jXvmcOqjeoQ" target="_596lbPtaEe2jXvmcOqjeoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_596lf_taEe2jXvmcOqjeoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_596lgPtaEe2jXvmcOqjeoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_596lgftaEe2jXvmcOqjeoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_596lgvtaEe2jXvmcOqjeoQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
